#!/bin/bash

if [ "$#" -ne 3 ]; then
  >&2 echo "Usage: git-repos-sync <repository URL> <repository URL> <branch-to-sync>"
  exit 1
fi

left="$1"
right="$2"
branch="$3"

if [ ! -d ".git" ]; then
  echo "Git repo for synchronization is not found, creating one..."
  git init
  git fetch "${left}"
  git checkout -b master FETCH_HEAD
  echo
fi

if ! git diff-index --quiet HEAD --; then
  >&2 echo "Local modifications found, looks like your in the conflict resolution. Resolve a conflict and commit. Then rerun script."
  exit 1
fi

echo "Left: ${left}"
echo "Right: ${right}"
echo
echo "Fetch latest commits from branch '${branch}' in '${left}'"
if ! git fetch -u "${left}" "${branch}:left/${branch}"; then
  >&2 echo "Fatal: unable to fetch from '${left}', rerun the script as soon as connection restored."
  exit 1
fi
echo "Fetch latest commits from branch ${branch} in ${right}"
if ! git fetch -u "${right}" "${branch}:right/${branch}"; then
  >&2 echo "Fatal: unable to fetch from '${right}', rerun the script as soon as connection restored."
  exit 1
fi
if git checkout --quiet -b "sync-${branch}" "right/${branch}"; then
  echo "Merge branches from left and right if necessary."
  if ! git merge -m "Merge to sync between '${left}' and '${right}'" --log "left/${branch}"; then
    >&2 echo "Merge conflict. Manual resolution needed, commit and rerun script."
    exit 1
  fi
else
  echo "Rerun after merge conflict resolution or restored connection."
  git checkout --quiet "sync-${branch}"
  echo "Try to merge with right first"
  if ! git merge -m "Merge to sync between '${left}' and '${right}'" --log "right/${branch}"; then
    >&2 echo "Merge conflict. Manual resolution needed, commit and rerun script."
    exit 1
  fi
  if ! git merge -m "Merge to sync between '${left}' and '${right}'" --log "left/${branch}"; then
    >&2 echo "Merge conflict. Manual resolution needed, commit and rerun script."
    exit 1
  fi
fi

echo "Push merged changes in '${branch}' to '${right}'"
if ! git push "${right}" "HEAD:${branch}" --tags; then
  >&2 echo "Fatal: unable to push to '${right}', rerun the script as soon as connection restored."
  exit 1
fi
echo "Push merged changes in '${branch}' to '${left}'"
if ! git push "${left}" "HEAD:${branch}" --tags; then
  >&2 echo "Fatal: unable to push to '${left}', rerun the script as soon as connection restored."
  exit 1
fi

git checkout --quiet master
git branch -D --quiet "sync-${branch}"

echo "Done."
