---
name: pre-commit
on:
  push:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      RAW_LOG: pre-commit.log
      CS_XML: pre-commit.xml
    steps:
      - run: sudo apt-get update && sudo apt-get install cppcheck
        if: false
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        if: false
        with:
          cache: pip
          python-version: 3.12.1
      - run: python -m pip install pre-commit regex
      - uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cache/pre-commit/
          key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml')
            }}
      - name: Convert Raw Log to annotations
        uses: mdeweerd/logToCheckStyle@v2024.3.5
        if: ${{ failure() }}
        with:
          in: ${{ env.RAW_LOG }}
          # Out can be omitted if you do not need the xml output
          # out: ${{ env.CS_XML }}

      - uses: actions/cache/save@v4
        if: ${{ always() }}
        with:
          path: |
            ~/.cache/pre-commit/
          key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml')
            }}
      - name: Provide log as artifact
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: precommit-logs
          path: |
            ${{ env.RAW_LOG }}
            ${{ env.CS_XML }}
          retention-days: 2
